### ISSUE TITLE
Error on upgrading to module version 2.1.2

### ISSUE THREAD

**Issue by stephenkenny** [derdanne/puppet-nfs#99]
Hi, we're running into trouble when we upgrade derdanne-nfs from v2.0.10 to v2.1.2 on our Puppet server.    Our machines are running Debian 9 (stretch), and our Puppet server and nodes are running Puppet version 6.2.

We've a simple NFS server config set up on a test server; this server is a Puppet node that declares the "nfs" class and gets its small amount of data via Hiera.  Everything works ok under v2.0.10.  For the record, the Hiera data is as follows:

`nfs::server_enabled: true`
`nfs::client_enabled :  false`
`nfs::nfs_v4:  true`
`nfs::nfs_v4_idmap_domain: 'scss.tcd.ie'`
`nfs::nfs_v4_export_root:  '/share'`
`nfs::nfs_v4_export_root_clients:`  `'testclient.scss.tcd.ie(rw,fsid=root,insecure,no_subtree_check,async,no_root_squash)'`

However, after upgrading to 2.1.2, the agent run on the test NFS server throws this error:

`Error: /Stage[main]/Nfs::Server::Config/Augeas[/etc/idmapd.conf]: Could not evaluate: undefined method 'strip!' for nil:NilClass`

Would greatly appreciate any assistance.

Thanks
Stephen (skenny@scss.tcd.ie)

**Comment by derdanne** [comment]
Hey,

i think you ran into this regression with puppet agent 6.2: https://tickets.puppetlabs.com/browse/PA-2433. Can you please retest this with a puppet agent from the 6.0.x branch?

**Comment by stephenkenny** [comment]
Ah ... ok.  I'll try that and will report back.   Many thanks.

**Comment by derdanne** [comment]
I've replaced the delete_undef_values with the native filter function in the develop branch for the augeas resource on the idmapd.conf, you can try if this fixes your problem.

**Comment by stephenkenny** [comment]
Hi, I downgraded my version of puppet-agent to 6.0.5 as you suggested, and that worked - I get a clean run of the agent now without the error.    We can hold to that version until, I guess, the Puppet developers fix their PA-2433 issue, so that represents a good fix for us.  

Many thanks.

**Comment by derdanne** [comment]
Thanks for investigating.
